//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.3.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
// Templates version: 
//////////////////////////////////////////////////////////////
using System;

namespace EntityModel
{
	/// <summary>Index enum to fast-access EntityFields in the IEntityFields collection for the entity: Collection.</summary>
	public enum CollectionFieldIndex
	{
		///<summary>Id. </summary>
		Id,
		///<summary>Name. </summary>
		Name,
		/// <summary></summary>
		AmountOfFields
	}
	/// <summary>Index enum to fast-access EntityFields in the IEntityFields collection for the entity: Item.</summary>
	public enum ItemFieldIndex
	{
		///<summary>CollectionId. </summary>
		CollectionId,
		///<summary>Description. </summary>
		Description,
		///<summary>Id. </summary>
		Id,
		/// <summary></summary>
		AmountOfFields
	}
	/// <summary>Index enum to fast-access EntityFields in the IEntityFields collection for the entity: DomainItem.</summary>
	public enum DomainItemFieldIndex
	{
		///<summary>CollectionId. Inherited from Item</summary>
		CollectionId,
		///<summary>Description. Inherited from Item</summary>
		Description,
		///<summary>Id. Inherited from Item</summary>
		Id_Item,
		///<summary>Id. </summary>
		Id,
		///<summary>OldItemId. </summary>
		OldItemId,
		/// <summary></summary>
		AmountOfFields
	}
	/// <summary>Index enum to fast-access EntityFields in the IEntityFields collection for the entity: SpecificItem.</summary>
	public enum SpecificItemFieldIndex
	{
		///<summary>CollectionId. Inherited from Item</summary>
		CollectionId,
		///<summary>Description. Inherited from Item</summary>
		Description,
		///<summary>Id. Inherited from Item</summary>
		Id_Item,
		///<summary>Id. Inherited from DomainItem</summary>
		Id_DomainItem,
		///<summary>OldItemId. Inherited from DomainItem</summary>
		OldItemId,
		///<summary>Id. </summary>
		Id,
		///<summary>Note. </summary>
		Note,
		/// <summary></summary>
		AmountOfFields
	}



	/// <summary>Enum definition for all the entity types defined in this namespace. Used by the entityfields factory.</summary>
	public enum EntityType
	{
		///<summary>Collection</summary>
		CollectionEntity,
		///<summary>Item</summary>
		ItemEntity,
		///<summary>DomainItem</summary>
		DomainItemEntity,
		///<summary>SpecificItem</summary>
		SpecificItemEntity
	}


	#region Custom ConstantsEnums Code
	
	// __LLBLGENPRO_USER_CODE_REGION_START CustomUserConstants
	// __LLBLGENPRO_USER_CODE_REGION_END
	#endregion

	#region Included code

	#endregion
}

