//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.3.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;

namespace EntityModel.TypedListClasses
{
	/// <summary>Class which represents a row in the typed list 'Specific.SpecificItemTypedList'.</summary>
	/// <remarks>This class is a result class for a query, which is produced with the method <see cref="EntityModel.Linq.LinqMetaData.GetSpecificItemTypedListTypedList"/>.
	/// Contains the following entity definition(s):
	/// Entity: Specific.SpecificItem. <br/>
	/// Custom Properties: <br/>
	/// </remarks>
	[Serializable]
	public partial class SpecificItemTypedListRow 
	{
		#region Extensibility Method Definitions
		partial void OnCreated();
		#endregion
		
		/// <summary>Initializes a new instance of the <see cref="SpecificItemTypedListRow"/> class.</summary>
		public SpecificItemTypedListRow()
		{
			OnCreated();
		}

		#region Class Property Declarations
		/// <summary>Gets or sets the CollectionId field. Mapped onto 'Specific.SpecificItem.CollectionId'</summary>
		public System.Int32 CollectionId { get; set; }
		/// <summary>Gets or sets the Description field. Mapped onto 'Specific.SpecificItem.Description'</summary>
		public System.String Description { get; set; }
		/// <summary>Gets or sets the Id field. Mapped onto 'Specific.SpecificItem.Id'</summary>
		public System.Int32 Id { get; set; }
		/// <summary>Gets or sets the Note field. Mapped onto 'Specific.SpecificItem.Note'</summary>
		public System.String Note { get; set; }
		/// <summary>Gets or sets the OldItemId field. Mapped onto 'Specific.SpecificItem.OldItemId'</summary>
		public System.Int32 OldItemId { get; set; }
		#endregion
	}
}

