//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.3.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Dto.Persistence
{
	/// <summary>Static class for (extension) methods for fetching and projecting instances of Dto.DtoClasses.SpecificItemDto from / to the entity model.</summary>
	public static partial class SpecificItemDtoPersistence
	{
		#region Statics
		private static readonly System.Linq.Expressions.Expression<Func<EntityModel.EntityClasses.SpecificItemEntity, Dto.DtoClasses.SpecificItemDto>> _projectorExpression = CreateProjectionFunc();
		private static readonly Func<EntityModel.EntityClasses.SpecificItemEntity, Dto.DtoClasses.SpecificItemDto> _compiledProjector = CreateProjectionFunc().Compile();
		#endregion	
	
		/// <summary>Empty static ctor for triggering initialization of static members in a thread-safe manner</summary>
		static SpecificItemDtoPersistence()
		{
		}
	
		/// <summary>Extension method which produces a projection to Dto.DtoClasses.SpecificItemDto which instances are projected from the 
		/// results of the specified baseQuery, which returns EntityModel.EntityClasses.SpecificItemEntity instances, the root entity of the derived element returned by this query.</summary>
		/// <param name="baseQuery">The base query to project the derived element instances from.</param>
		/// <returns>IQueryable to retrieve Dto.DtoClasses.SpecificItemDto instances</returns>
		public static IQueryable<Dto.DtoClasses.SpecificItemDto> ProjectToSpecificItemDto(this IQueryable<EntityModel.EntityClasses.SpecificItemEntity> baseQuery)
		{
			return baseQuery.Select(_projectorExpression);
		}
		
		
		/// <summary>Extension method which produces a projection to Dto.DtoClasses.SpecificItemDto which instances are projected from the
		/// EntityModel.EntityClasses.SpecificItemEntity entity instance specified, the root entity of the derived element returned by this method.</summary>
		/// <param name="entity">The entity to project from.</param>
		/// <returns>EntityModel.EntityClasses.SpecificItemEntity instance created from the specified entity instance</returns>
		public static Dto.DtoClasses.SpecificItemDto ProjectToSpecificItemDto(this EntityModel.EntityClasses.SpecificItemEntity entity)
		{
			return _compiledProjector(entity);
		}

		
		private static System.Linq.Expressions.Expression<Func<EntityModel.EntityClasses.SpecificItemEntity, Dto.DtoClasses.SpecificItemDto>> CreateProjectionFunc()
		{
			return p__0 => new Dto.DtoClasses.SpecificItemDto()
			{
				Collection = new Dto.DtoClasses.SpecificItemDtoTypes.Collection()
				{
					Id = p__0.Collection.Id,
					Name = p__0.Collection.Name,
				},
				CollectionId = p__0.CollectionId,
				Description = p__0.Description,
				Id = p__0.Id,
				Incidents = p__0.Incidents.Select(p__1 => new Dto.DtoClasses.SpecificItemDtoTypes.Incident()
				{
					ActorIncidents = p__1.ActorIncidents.Select(p__2 => new Dto.DtoClasses.SpecificItemDtoTypes.IncidentTypes.ActorIncident()
					{
						Actor = new Dto.DtoClasses.SpecificItemDtoTypes.IncidentTypes.ActorIncidentTypes.Actor()
						{
							CollectionId = p__2.Actor.CollectionId,
							Id = p__2.Actor.Id,
						},
						ActorId = p__2.ActorId,
						Id = p__2.Id,
						IncidentId = p__2.IncidentId,
					}).ToList(),
					Grouping = p__1.Grouping,
					Id = p__1.Id,
				}).ToList(),
				Note = p__0.Note,
				OldItemId = p__0.OldItemId,
			};
		}
		
		

		/// <summary>Creates a primary key predicate to be used in a Where() clause in a Linq query which is executed on the database to fetch the original entity instance
		/// the specified <see cref="dto"/> object was projected from.</summary>
		/// <param name="dto">The dto object for which the primary key predicate has to be created for.</param>
		/// <returns>ready to use expression</returns>
		public static System.Linq.Expressions.Expression<Func<EntityModel.EntityClasses.SpecificItemEntity, bool>> CreatePkPredicate(Dto.DtoClasses.SpecificItemDto dto)
		{
			return p__0 => p__0.Id == dto.Id;
		}

		/// <summary>Creates a primary key predicate to be used in a Where() clause in a Linq query which is executed on the database to fetch the original entity instances
		/// the specified set of <see cref="dtos"/> objects was projected from.</summary>
		/// <param name="dtos">The dto objects for which the primary key predicate has to be created for.</param>
		/// <returns>ready to use expression</returns>
		public static System.Linq.Expressions.Expression<Func<EntityModel.EntityClasses.SpecificItemEntity, bool>> CreatePkPredicate(IEnumerable<Dto.DtoClasses.SpecificItemDto> dtos)
		{
			var ids = dtos.Select(p__1=>p__1.Id).ToList();
			return p__0 => ids.Contains(p__0.Id);
		}

		/// <summary>Creates a primary key predicate to be used in a Where() clause in a Linq query on an IEnumerable in-memory set of entity instances
		/// to retrieve the original entity instance the specified <see cref="dto"/> object was projected from.</summary>
		/// <param name="dto">The dto object for which the primary key predicate has to be created for.</param>
		/// <returns>ready to use func</returns>
		public static Func<EntityModel.EntityClasses.SpecificItemEntity, bool> CreateInMemoryPkPredicate(Dto.DtoClasses.SpecificItemDto dto)
		{
			return p__0 => p__0.Id == dto.Id;
		}
		
		/// <summary>Updates the specified EntityModel.EntityClasses.SpecificItemEntity entity with the values stored in the dto object specified</summary>
		/// <param name="toUpdate">the entity instance to update.</param>
		/// <param name="dto">The dto object containing the source values.</param>
		/// <remarks>The PK field of toUpdate is set only if it's not marked as readonly.</remarks>
		public static void UpdateFromSpecificItemDto(this EntityModel.EntityClasses.SpecificItemEntity toUpdate, Dto.DtoClasses.SpecificItemDto dto)
		{
			if((toUpdate == null) || (dto==null))
			{
				return;
			}
			toUpdate.CollectionId = dto.CollectionId;
			toUpdate.Description = dto.Description;
			toUpdate.Id = dto.Id;
			toUpdate.Note = dto.Note;
			toUpdate.OldItemId = dto.OldItemId;
		}
	}
}


 