//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.3.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Collections.Generic;

namespace Dto.DtoClasses
{ 
	/// <summary> DTO class which is derived from the entity 'Actor.Person'.</summary>
	[Serializable]
	[DataContract]
	public partial class ActorPersonDto
	{
		/// <summary>Gets or sets the CollectionId field. Derived from Entity Model Field 'Core.Actor.CollectionId (FK)'</summary>
		[DataMember]
		public System.Int32 CollectionId { get; set; }
		/// <summary>Gets or sets the Firstname field. Derived from Entity Model Field 'Actor.Person.Firstname'</summary>
		[DataMember]
		public System.String Firstname { get; set; }
		/// <summary>Gets or sets the Id field. Derived from Entity Model Field 'Core.Actor.Id'</summary>
		[DataMember]
		public System.Int32 Id { get; set; }
		/// <summary>Gets or sets the Lastname field. Derived from Entity Model Field 'Actor.Person.Lastname'</summary>
		[DataMember]
		public System.String Lastname { get; set; }
	}

}




