//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.3.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Collections.Generic;

namespace Dto.DtoClasses
{ 
	/// <summary> DTO class which is derived from the entity 'Core.Collection'.</summary>
	[Serializable]
	[DataContract]
	public partial class CoreCollectionDto
	{
		/// <summary>Gets or sets the Id field. Derived from Entity Model Field 'Core.Collection.Id'</summary>
		[DataMember]
		public System.Int32 Id { get; set; }
		/// <summary>Gets or sets the Name field. Derived from Entity Model Field 'Core.Collection.Name'</summary>
		[DataMember]
		public System.String Name { get; set; }
	}

}




