//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.3.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Collections.Generic;

namespace Dto.DtoClasses
{ 
	/// <summary> DTO class which is derived from the entity 'Core.Incident'.</summary>
	[Serializable]
	[DataContract]
	public partial class CoreIncidentDto
	{
		/// <summary>Gets or sets the CollectionId field. Derived from Entity Model Field 'Core.Incident.CollectionId (FK)'</summary>
		[DataMember]
		public System.Int32 CollectionId { get; set; }
		/// <summary>Gets or sets the Grouping field. Derived from Entity Model Field 'Core.Incident.Grouping'</summary>
		[DataMember]
		public Nullable<System.Int32> Grouping { get; set; }
		/// <summary>Gets or sets the Id field. Derived from Entity Model Field 'Core.Incident.Id'</summary>
		[DataMember]
		public System.Int32 Id { get; set; }
		/// <summary>Gets or sets the ItemId field. Derived from Entity Model Field 'Core.Incident.ItemId (FK)'</summary>
		[DataMember]
		public System.Int32 ItemId { get; set; }
	}

}




