//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.3.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Collections.Generic;

namespace Dto.DtoClasses
{ 
	/// <summary> DTO class which is derived from the entity 'Core.ActorIncident'.</summary>
	[Serializable]
	[DataContract]
	public partial class CoreActorIncidentDto
	{
		/// <summary>Gets or sets the ActorId field. Derived from Entity Model Field 'Core.ActorIncident.ActorId (FK)'</summary>
		[DataMember]
		public System.Int32 ActorId { get; set; }
		/// <summary>Gets or sets the Id field. Derived from Entity Model Field 'Core.ActorIncident.Id'</summary>
		[DataMember]
		public System.Int32 Id { get; set; }
		/// <summary>Gets or sets the IncidentId field. Derived from Entity Model Field 'Core.ActorIncident.IncidentId (FK)'</summary>
		[DataMember]
		public System.Int32 IncidentId { get; set; }
	}

}




