//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.3.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Collections.Generic;

namespace Dto.DtoClasses
{ 
	/// <summary> DTO class which is derived from the entity 'Specific.SpecificItem'.</summary>
	[Serializable]
	[DataContract]
	public partial class SpecificItemDto
	{
		/// <summary>Gets or sets the Collection field. </summary>
		[DataMember]
		public SpecificItemDtoTypes.Collection Collection { get; set; }
		/// <summary>Gets or sets the CollectionId field. Derived from Entity Model Field 'Core.Item.CollectionId (FK)'</summary>
		[DataMember]
		public System.Int32 CollectionId { get; set; }
		/// <summary>Gets or sets the Description field. Derived from Entity Model Field 'Core.Item.Description'</summary>
		[DataMember]
		public System.String Description { get; set; }
		/// <summary>Gets or sets the Id field. Derived from Entity Model Field 'Core.Item.Id'</summary>
		[DataMember]
		public System.Int32 Id { get; set; }
		/// <summary>Gets or sets the Note field. Derived from Entity Model Field 'Specific.SpecificItem.Note'</summary>
		[DataMember]
		public System.String Note { get; set; }
		/// <summary>Gets or sets the OldItemId field. Derived from Entity Model Field 'Domain.DomainItem.OldItemId'</summary>
		[DataMember]
		public System.Int32 OldItemId { get; set; }
	}

	namespace SpecificItemDtoTypes
	{
		/// <summary> DTO class which is derived from the entity 'Core.Collection (Collection)'.</summary>
		[Serializable]
		[DataContract]
		public partial class Collection
		{
			/// <summary>Gets or sets the Id field. Derived from Entity Model Field 'Core.Collection.Id'</summary>
			[DataMember]
			public System.Int32 Id { get; set; }
			/// <summary>Gets or sets the Name field. Derived from Entity Model Field 'Core.Collection.Name'</summary>
			[DataMember]
			public System.String Name { get; set; }
		}
	}

}




