//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.3.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
// Templates version: 
//////////////////////////////////////////////////////////////
using System;
using System.Collections;
using System.Collections.Generic;
using EntityModel;
using EntityModel.FactoryClasses;
using EntityModel.HelperClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace EntityModel.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: ActorIncident. </summary>
	public partial class ActorIncidentRelations
	{
		/// <summary>CTor</summary>
		public ActorIncidentRelations()
		{
		}

		/// <summary>Gets all relations of the ActorIncidentEntity as a list of IEntityRelation objects.</summary>
		/// <returns>a list of IEntityRelation objects</returns>
		public virtual List<IEntityRelation> GetAllRelations()
		{
			List<IEntityRelation> toReturn = new List<IEntityRelation>();
			toReturn.Add(this.ActorEntityUsingActorId);
			toReturn.Add(this.IncidentEntityUsingIncidentId);
			return toReturn;
		}

		#region Class Property Declarations



		/// <summary>Returns a new IEntityRelation object, between ActorIncidentEntity and ActorEntity over the m:1 relation they have, using the relation between the fields:
		/// ActorIncident.ActorId - Actor.Id
		/// </summary>
		public virtual IEntityRelation ActorEntityUsingActorId
		{
			get
			{
				IEntityRelation relation = new EntityRelation(SD.LLBLGen.Pro.ORMSupportClasses.RelationType.ManyToOne, "Actor", false);
				relation.AddEntityFieldPair(ActorFields.Id, ActorIncidentFields.ActorId);
				relation.InheritanceInfoPkSideEntity = InheritanceInfoProviderSingleton.GetInstance().GetInheritanceInfo("ActorEntity", false);
				relation.InheritanceInfoFkSideEntity = InheritanceInfoProviderSingleton.GetInstance().GetInheritanceInfo("ActorIncidentEntity", true);
				return relation;
			}
		}
		/// <summary>Returns a new IEntityRelation object, between ActorIncidentEntity and IncidentEntity over the m:1 relation they have, using the relation between the fields:
		/// ActorIncident.IncidentId - Incident.Id
		/// </summary>
		public virtual IEntityRelation IncidentEntityUsingIncidentId
		{
			get
			{
				IEntityRelation relation = new EntityRelation(SD.LLBLGen.Pro.ORMSupportClasses.RelationType.ManyToOne, "Incident", false);
				relation.AddEntityFieldPair(IncidentFields.Id, ActorIncidentFields.IncidentId);
				relation.InheritanceInfoPkSideEntity = InheritanceInfoProviderSingleton.GetInstance().GetInheritanceInfo("IncidentEntity", false);
				relation.InheritanceInfoFkSideEntity = InheritanceInfoProviderSingleton.GetInstance().GetInheritanceInfo("ActorIncidentEntity", true);
				return relation;
			}
		}
		/// <summary>stub, not used in this entity, only for TargetPerEntity entities.</summary>
		public virtual IEntityRelation GetSubTypeRelation(string subTypeEntityName) { return null; }
		/// <summary>stub, not used in this entity, only for TargetPerEntity entities.</summary>
		public virtual IEntityRelation GetSuperTypeRelation() { return null;}
		#endregion

		#region Included Code

		#endregion
	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticActorIncidentRelations
	{
		internal static readonly IEntityRelation ActorEntityUsingActorIdStatic = new ActorIncidentRelations().ActorEntityUsingActorId;
		internal static readonly IEntityRelation IncidentEntityUsingIncidentIdStatic = new ActorIncidentRelations().IncidentEntityUsingIncidentId;

		/// <summary>CTor</summary>
		static StaticActorIncidentRelations()
		{
		}
	}
}
