//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.3.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
// Templates version: 
//////////////////////////////////////////////////////////////
using System;
using System.Collections;
using System.Collections.Generic;
using EntityModel;
using EntityModel.FactoryClasses;
using EntityModel.HelperClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace EntityModel.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Actor. </summary>
	public partial class ActorRelations : IRelationFactory
	{
		/// <summary>CTor</summary>
		public ActorRelations()
		{
		}

		/// <summary>Gets all relations of the ActorEntity as a list of IEntityRelation objects.</summary>
		/// <returns>a list of IEntityRelation objects</returns>
		public virtual List<IEntityRelation> GetAllRelations()
		{
			List<IEntityRelation> toReturn = new List<IEntityRelation>();
			toReturn.Add(this.ActorIncidentEntityUsingActorId);
			toReturn.Add(this.CollectionEntityUsingCollectionId);
			return toReturn;
		}

		#region Class Property Declarations

		/// <summary>Returns a new IEntityRelation object, between ActorEntity and ActorIncidentEntity over the 1:n relation they have, using the relation between the fields:
		/// Actor.Id - ActorIncident.ActorId
		/// </summary>
		public virtual IEntityRelation ActorIncidentEntityUsingActorId
		{
			get
			{
				IEntityRelation relation = new EntityRelation(SD.LLBLGen.Pro.ORMSupportClasses.RelationType.OneToMany, "ActorIncidents" , true);
				relation.AddEntityFieldPair(ActorFields.Id, ActorIncidentFields.ActorId);
				relation.InheritanceInfoPkSideEntity = InheritanceInfoProviderSingleton.GetInstance().GetInheritanceInfo("ActorEntity", true);
				relation.InheritanceInfoFkSideEntity = InheritanceInfoProviderSingleton.GetInstance().GetInheritanceInfo("ActorIncidentEntity", false);
				return relation;
			}
		}


		/// <summary>Returns a new IEntityRelation object, between ActorEntity and CollectionEntity over the m:1 relation they have, using the relation between the fields:
		/// Actor.CollectionId - Collection.Id
		/// </summary>
		public virtual IEntityRelation CollectionEntityUsingCollectionId
		{
			get
			{
				IEntityRelation relation = new EntityRelation(SD.LLBLGen.Pro.ORMSupportClasses.RelationType.ManyToOne, "Collection", false);
				relation.AddEntityFieldPair(CollectionFields.Id, ActorFields.CollectionId);
				relation.InheritanceInfoPkSideEntity = InheritanceInfoProviderSingleton.GetInstance().GetInheritanceInfo("CollectionEntity", false);
				relation.InheritanceInfoFkSideEntity = InheritanceInfoProviderSingleton.GetInstance().GetInheritanceInfo("ActorEntity", true);
				return relation;
			}
		}



		/// <summary>Returns a new IEntityRelation object, between ActorEntity and PersonEntity over the 1:1 relation they have, which is used to build a target per entity hierarchy</summary>		
		internal IEntityRelation RelationToSubTypePersonEntity
		{
			get
			{
				IEntityRelation relation = new EntityRelation(SD.LLBLGen.Pro.ORMSupportClasses.RelationType.OneToOne, true);
				relation.AddEntityFieldPair(ActorFields.Id, PersonFields.Id);
				relation.IsHierarchyRelation=true;
				return relation;
			}
		}
		
		/// <summary>Returns the relation object the entity, to which this relation factory belongs, has with the subtype with the specified name</summary>
		/// <param name="subTypeEntityName">name of direct subtype which is a subtype of the current entity through the relation to return.</param>
		/// <returns>relation which makes the current entity a supertype of the subtype entity with the name specified, or null if not applicable/found</returns>
		public virtual IEntityRelation GetSubTypeRelation(string subTypeEntityName)
		{
			switch(subTypeEntityName)
			{
				case "PersonEntity":
					return this.RelationToSubTypePersonEntity;
				default:
					return null;
			}
		}
		
		/// <summary>Returns the relation object the entity, to which this relation factory belongs, has with its supertype, if applicable.</summary>
		/// <returns>relation which makes the current entity a subtype of its supertype entity or null if not applicable/found</returns>
		public virtual IEntityRelation GetSuperTypeRelation()
		{
			return null;
		}

		#endregion

		#region Included Code

		#endregion
	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticActorRelations
	{
		internal static readonly IEntityRelation ActorIncidentEntityUsingActorIdStatic = new ActorRelations().ActorIncidentEntityUsingActorId;
		internal static readonly IEntityRelation CollectionEntityUsingCollectionIdStatic = new ActorRelations().CollectionEntityUsingCollectionId;

		/// <summary>CTor</summary>
		static StaticActorRelations()
		{
		}
	}
}
