//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.3.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
// Templates version: 
//////////////////////////////////////////////////////////////
using System;
using System.Collections;
using System.Collections.Generic;
using EntityModel;
using EntityModel.FactoryClasses;
using EntityModel.HelperClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace EntityModel.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Collection. </summary>
	public partial class CollectionRelations
	{
		/// <summary>CTor</summary>
		public CollectionRelations()
		{
		}

		/// <summary>Gets all relations of the CollectionEntity as a list of IEntityRelation objects.</summary>
		/// <returns>a list of IEntityRelation objects</returns>
		public virtual List<IEntityRelation> GetAllRelations()
		{
			List<IEntityRelation> toReturn = new List<IEntityRelation>();
			toReturn.Add(this.ItemEntityUsingCollectionId);
			return toReturn;
		}

		#region Class Property Declarations

		/// <summary>Returns a new IEntityRelation object, between CollectionEntity and ItemEntity over the 1:n relation they have, using the relation between the fields:
		/// Collection.Id - Item.CollectionId
		/// </summary>
		public virtual IEntityRelation ItemEntityUsingCollectionId
		{
			get
			{
				IEntityRelation relation = new EntityRelation(SD.LLBLGen.Pro.ORMSupportClasses.RelationType.OneToMany, "Items" , true);
				relation.AddEntityFieldPair(CollectionFields.Id, ItemFields.CollectionId);
				relation.InheritanceInfoPkSideEntity = InheritanceInfoProviderSingleton.GetInstance().GetInheritanceInfo("CollectionEntity", true);
				relation.InheritanceInfoFkSideEntity = InheritanceInfoProviderSingleton.GetInstance().GetInheritanceInfo("ItemEntity", false);
				return relation;
			}
		}


		/// <summary>stub, not used in this entity, only for TargetPerEntity entities.</summary>
		public virtual IEntityRelation GetSubTypeRelation(string subTypeEntityName) { return null; }
		/// <summary>stub, not used in this entity, only for TargetPerEntity entities.</summary>
		public virtual IEntityRelation GetSuperTypeRelation() { return null;}
		#endregion

		#region Included Code

		#endregion
	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticCollectionRelations
	{
		internal static readonly IEntityRelation ItemEntityUsingCollectionIdStatic = new CollectionRelations().ItemEntityUsingCollectionId;

		/// <summary>CTor</summary>
		static StaticCollectionRelations()
		{
		}
	}
}
