//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.3.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
// Templates version: 
//////////////////////////////////////////////////////////////
using System;
using System.Collections;
using System.Collections.Generic;
using EntityModel;
using EntityModel.FactoryClasses;
using EntityModel.HelperClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace EntityModel.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Incident. </summary>
	public partial class IncidentRelations
	{
		/// <summary>CTor</summary>
		public IncidentRelations()
		{
		}

		/// <summary>Gets all relations of the IncidentEntity as a list of IEntityRelation objects.</summary>
		/// <returns>a list of IEntityRelation objects</returns>
		public virtual List<IEntityRelation> GetAllRelations()
		{
			List<IEntityRelation> toReturn = new List<IEntityRelation>();
			toReturn.Add(this.ActorIncidentEntityUsingIncidentId);
			toReturn.Add(this.CollectionEntityUsingCollectionId);
			toReturn.Add(this.ItemEntityUsingItemId);
			return toReturn;
		}

		#region Class Property Declarations

		/// <summary>Returns a new IEntityRelation object, between IncidentEntity and ActorIncidentEntity over the 1:n relation they have, using the relation between the fields:
		/// Incident.Id - ActorIncident.IncidentId
		/// </summary>
		public virtual IEntityRelation ActorIncidentEntityUsingIncidentId
		{
			get
			{
				IEntityRelation relation = new EntityRelation(SD.LLBLGen.Pro.ORMSupportClasses.RelationType.OneToMany, "ActorIncidents" , true);
				relation.AddEntityFieldPair(IncidentFields.Id, ActorIncidentFields.IncidentId);
				relation.InheritanceInfoPkSideEntity = InheritanceInfoProviderSingleton.GetInstance().GetInheritanceInfo("IncidentEntity", true);
				relation.InheritanceInfoFkSideEntity = InheritanceInfoProviderSingleton.GetInstance().GetInheritanceInfo("ActorIncidentEntity", false);
				return relation;
			}
		}


		/// <summary>Returns a new IEntityRelation object, between IncidentEntity and CollectionEntity over the m:1 relation they have, using the relation between the fields:
		/// Incident.CollectionId - Collection.Id
		/// </summary>
		public virtual IEntityRelation CollectionEntityUsingCollectionId
		{
			get
			{
				IEntityRelation relation = new EntityRelation(SD.LLBLGen.Pro.ORMSupportClasses.RelationType.ManyToOne, "Collection", false);
				relation.AddEntityFieldPair(CollectionFields.Id, IncidentFields.CollectionId);
				relation.InheritanceInfoPkSideEntity = InheritanceInfoProviderSingleton.GetInstance().GetInheritanceInfo("CollectionEntity", false);
				relation.InheritanceInfoFkSideEntity = InheritanceInfoProviderSingleton.GetInstance().GetInheritanceInfo("IncidentEntity", true);
				return relation;
			}
		}
		/// <summary>Returns a new IEntityRelation object, between IncidentEntity and ItemEntity over the m:1 relation they have, using the relation between the fields:
		/// Incident.ItemId - Item.Id
		/// </summary>
		public virtual IEntityRelation ItemEntityUsingItemId
		{
			get
			{
				IEntityRelation relation = new EntityRelation(SD.LLBLGen.Pro.ORMSupportClasses.RelationType.ManyToOne, "Item", false);
				relation.AddEntityFieldPair(ItemFields.Id, IncidentFields.ItemId);
				relation.InheritanceInfoPkSideEntity = InheritanceInfoProviderSingleton.GetInstance().GetInheritanceInfo("ItemEntity", false);
				relation.InheritanceInfoFkSideEntity = InheritanceInfoProviderSingleton.GetInstance().GetInheritanceInfo("IncidentEntity", true);
				return relation;
			}
		}
		/// <summary>stub, not used in this entity, only for TargetPerEntity entities.</summary>
		public virtual IEntityRelation GetSubTypeRelation(string subTypeEntityName) { return null; }
		/// <summary>stub, not used in this entity, only for TargetPerEntity entities.</summary>
		public virtual IEntityRelation GetSuperTypeRelation() { return null;}
		#endregion

		#region Included Code

		#endregion
	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticIncidentRelations
	{
		internal static readonly IEntityRelation ActorIncidentEntityUsingIncidentIdStatic = new IncidentRelations().ActorIncidentEntityUsingIncidentId;
		internal static readonly IEntityRelation CollectionEntityUsingCollectionIdStatic = new IncidentRelations().CollectionEntityUsingCollectionId;
		internal static readonly IEntityRelation ItemEntityUsingItemIdStatic = new IncidentRelations().ItemEntityUsingItemId;

		/// <summary>CTor</summary>
		static StaticIncidentRelations()
		{
		}
	}
}
