//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.3.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.Linq;
using System.Collections.Generic;
using SD.LLBLGen.Pro.LinqSupportClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;

using EntityModel;
using EntityModel.EntityClasses;
using EntityModel.FactoryClasses;
using EntityModel.HelperClasses;
using EntityModel.RelationClasses;

namespace EntityModel.Linq
{
	/// <summary>Meta-data class for the construction of Linq queries which are to be executed using LLBLGen Pro code.</summary>
	public partial class LinqMetaData: ILinqMetaData
	{
		#region Class Member Declarations
		private IDataAccessAdapter _adapterToUse;
		private FunctionMappingStore _customFunctionMappings;
		private Context _contextToUse;
		#endregion
		
		/// <summary>CTor. Using this ctor will leave the IDataAccessAdapter object to use empty. To be able to execute the query, an IDataAccessAdapter instance
		/// is required, and has to be set on the LLBLGenProProvider2 object in the query to execute. </summary>
		public LinqMetaData() : this(null, null)
		{
		}
		
		/// <summary>CTor which accepts an IDataAccessAdapter implementing object, which will be used to execute queries created with this metadata class.</summary>
		/// <param name="adapterToUse">the IDataAccessAdapter to use in queries created with this meta data</param>
		/// <remarks> Be aware that the IDataAccessAdapter object set via this property is kept alive by the LLBLGenProQuery objects created with this meta data
		/// till they go out of scope.</remarks>
		public LinqMetaData(IDataAccessAdapter adapterToUse) : this (adapterToUse, null)
		{
		}

		/// <summary>CTor which accepts an IDataAccessAdapter implementing object, which will be used to execute queries created with this metadata class.</summary>
		/// <param name="adapterToUse">the IDataAccessAdapter to use in queries created with this meta data</param>
		/// <param name="customFunctionMappings">The custom function mappings to use. These take higher precedence than the ones in the DQE to use.</param>
		/// <remarks> Be aware that the IDataAccessAdapter object set via this property is kept alive by the LLBLGenProQuery objects created with this meta data
		/// till they go out of scope.</remarks>
		public LinqMetaData(IDataAccessAdapter adapterToUse, FunctionMappingStore customFunctionMappings)
		{
			_adapterToUse = adapterToUse;
			_customFunctionMappings = customFunctionMappings;
		}
	
		/// <summary>returns the datasource to use in a Linq query for the entity type specified</summary>
		/// <param name="typeOfEntity">the type of the entity to get the datasource for</param>
		/// <returns>the requested datasource</returns>
		public IDataSource GetQueryableForEntity(int typeOfEntity)
		{
			IDataSource toReturn = null;
			switch((EntityModel.EntityType)typeOfEntity)
			{
				case EntityModel.EntityType.PersonEntity:
					toReturn = this.Person;
					break;
				case EntityModel.EntityType.ActorEntity:
					toReturn = this.Actor;
					break;
				case EntityModel.EntityType.ActorIncidentEntity:
					toReturn = this.ActorIncident;
					break;
				case EntityModel.EntityType.CollectionEntity:
					toReturn = this.Collection;
					break;
				case EntityModel.EntityType.IncidentEntity:
					toReturn = this.Incident;
					break;
				case EntityModel.EntityType.ItemEntity:
					toReturn = this.Item;
					break;
				case EntityModel.EntityType.DomainItemEntity:
					toReturn = this.DomainItem;
					break;
				case EntityModel.EntityType.SpecificItemEntity:
					toReturn = this.SpecificItem;
					break;
				default:
					toReturn = null;
					break;
			}
			return toReturn;
		}

		/// <summary>returns the datasource to use in a Linq query for the entity type specified</summary>
		/// <typeparam name="TEntity">the type of the entity to get the datasource for</typeparam>
		/// <returns>the requested datasource</returns>
		public DataSource2<TEntity> GetQueryableForEntity<TEntity>()
				where TEntity : class
		{
			return new DataSource2<TEntity>(_adapterToUse, new ElementCreator(), _customFunctionMappings, _contextToUse);
		}

		/// <summary>returns the datasource to use in a Linq query when targeting PersonEntity instances in the database.</summary>
		public DataSource2<PersonEntity> Person
		{
			get { return new DataSource2<PersonEntity>(_adapterToUse, new ElementCreator(), _customFunctionMappings, _contextToUse); }
		}
		
		/// <summary>returns the datasource to use in a Linq query when targeting ActorEntity instances in the database.</summary>
		public DataSource2<ActorEntity> Actor
		{
			get { return new DataSource2<ActorEntity>(_adapterToUse, new ElementCreator(), _customFunctionMappings, _contextToUse); }
		}
		
		/// <summary>returns the datasource to use in a Linq query when targeting ActorIncidentEntity instances in the database.</summary>
		public DataSource2<ActorIncidentEntity> ActorIncident
		{
			get { return new DataSource2<ActorIncidentEntity>(_adapterToUse, new ElementCreator(), _customFunctionMappings, _contextToUse); }
		}
		
		/// <summary>returns the datasource to use in a Linq query when targeting CollectionEntity instances in the database.</summary>
		public DataSource2<CollectionEntity> Collection
		{
			get { return new DataSource2<CollectionEntity>(_adapterToUse, new ElementCreator(), _customFunctionMappings, _contextToUse); }
		}
		
		/// <summary>returns the datasource to use in a Linq query when targeting IncidentEntity instances in the database.</summary>
		public DataSource2<IncidentEntity> Incident
		{
			get { return new DataSource2<IncidentEntity>(_adapterToUse, new ElementCreator(), _customFunctionMappings, _contextToUse); }
		}
		
		/// <summary>returns the datasource to use in a Linq query when targeting ItemEntity instances in the database.</summary>
		public DataSource2<ItemEntity> Item
		{
			get { return new DataSource2<ItemEntity>(_adapterToUse, new ElementCreator(), _customFunctionMappings, _contextToUse); }
		}
		
		/// <summary>returns the datasource to use in a Linq query when targeting DomainItemEntity instances in the database.</summary>
		public DataSource2<DomainItemEntity> DomainItem
		{
			get { return new DataSource2<DomainItemEntity>(_adapterToUse, new ElementCreator(), _customFunctionMappings, _contextToUse); }
		}
		
		/// <summary>returns the datasource to use in a Linq query when targeting SpecificItemEntity instances in the database.</summary>
		public DataSource2<SpecificItemEntity> SpecificItem
		{
			get { return new DataSource2<SpecificItemEntity>(_adapterToUse, new ElementCreator(), _customFunctionMappings, _contextToUse); }
		}
		

		/// <summary>Gets the query to fetch the typed list Specific.SpecificItemTypedList</summary>
		/// <returns>IQueryable</returns>
		public IQueryable<EntityModel.TypedListClasses.SpecificItemTypedListRow> GetSpecificItemTypedListTypedList()
		{
			var current0 = this.SpecificItem;
			return current0.Select(v=>new EntityModel.TypedListClasses.SpecificItemTypedListRow() { CollectionId = v.CollectionId, Description = v.Description, Id = v.Id, Note = v.Note, OldItemId = v.OldItemId });
		}

		#region Class Property Declarations
		/// <summary> Gets / sets the IDataAccessAdapter to use for the queries created with this meta data object.</summary>
		/// <remarks> Be aware that the IDataAccessAdapter object set via this property is kept alive by the LLBLGenProQuery objects created with this meta data
		/// till they go out of scope.</remarks>
		public IDataAccessAdapter AdapterToUse
		{
			get { return _adapterToUse;}
			set { _adapterToUse = value;}
		}

		/// <summary>Gets or sets the custom function mappings to use. These take higher precedence than the ones in the DQE to use</summary>
		public FunctionMappingStore CustomFunctionMappings
		{
			get { return _customFunctionMappings; }
			set { _customFunctionMappings = value; }
		}
		
		/// <summary>Gets or sets the Context instance to use for entity fetches.</summary>
		public Context ContextToUse
		{
			get { return _contextToUse;}
			set { _contextToUse = value;}
		}
		#endregion
	}
}