
-- ----------------------------------------------------------------------------------------------------------------
-- Generated by LLBLGen Pro v5.3  Build: 5.3.2
-- SQL Server DDL Script generated from project: Simple Model
-- Project filename: C:\Development\test-llblgen-webapi\Simple Model.llblgenproj
-- Script generated on: 28-feb-2018 14:40.13
--
-- This is a Create script for creating a NEW data model. If you want DDL SQL for updating an existing model,
-- please create an Update script instead. 
--
-- This script might create schemas, which requires you to assign a proper user to the schema. Adjust the CREATE SCHEMA
-- statements below, if any, to avoid errors at runtime. Schemas aren't dropped in the DROP section.
--
--      >>>>> WARNING <<<<<
--      This is a CREATE script, with DROP statements for the existing tables, foreign keys and other constraints
--      This means that existing tables, data, constraints and other elements in the catalog/schemas addressed
--      are deleted. Use this Create script only to create new schemas with tables/constraints and other elements.
--
-- ----------------------------------------------------------------------------------------------------------------
-- ###############################################################################################################
-- DROP statements for existing elements. 
-- ###############################################################################################################
-- DROP statements for dropping existing elements with the same names as the ones created are commented out below. 
-- If you want to enable these statements for DROPping the existing elements first (which will remove all the data
-- in these existing elements), uncomment these statements by removing the two comment markers /* and */

-- Remove the comment marker on the NEXT line to enable DROP statements to remove existing elements
/* 

USE [SimpleModel]
GO
-- ----------------------------------------------------------------------------------------------------------------
-- DROP Foreign keys
-- ----------------------------------------------------------------------------------------------------------------

ALTER TABLE [Actor].[Person] DROP CONSTRAINT [FK_930af9146f7891519bfd539719f]
GO

ALTER TABLE [Core].[Actor] DROP CONSTRAINT [FK_478661c40f1b8793b56a43db518]
GO

ALTER TABLE [Core].[ActorIncident] DROP CONSTRAINT [FK_86a475f4cfbb06ba18432b53145]
GO

ALTER TABLE [Core].[ActorIncident] DROP CONSTRAINT [FK_a7d67124e8d860cbdc9a4fb9950]
GO

ALTER TABLE [Core].[Incident] DROP CONSTRAINT [FK_fb86340495bb80a0ec59eb4d91a]
GO

ALTER TABLE [Core].[Incident] DROP CONSTRAINT [FK_fc9c98b4cffb675fe16927f55d6]
GO

ALTER TABLE [Core].[Item] DROP CONSTRAINT [FK_fc808344380a37dec4d633ada36]
GO

ALTER TABLE [Domain].[DomainItem] DROP CONSTRAINT [FK_d12edd44b5aa5f0bf22b311ec9f]
GO

ALTER TABLE [Specific].[SpecificItem] DROP CONSTRAINT [FK_ed0220f42cab80268e8722796c0]
GO
-- ----------------------------------------------------------------------------------------------------------------
-- DROP tables for schema 'Actor' 
-- ----------------------------------------------------------------------------------------------------------------

DROP TABLE [Actor].[Person]
GO
-- ----------------------------------------------------------------------------------------------------------------
-- DROP tables for schema 'Core' 
-- ----------------------------------------------------------------------------------------------------------------

DROP TABLE [Core].[Actor]
GO

DROP TABLE [Core].[ActorIncident]
GO

DROP TABLE [Core].[Collection]
GO

DROP TABLE [Core].[Incident]
GO

DROP TABLE [Core].[Item]
GO
-- ----------------------------------------------------------------------------------------------------------------
-- DROP tables for schema 'Domain' 
-- ----------------------------------------------------------------------------------------------------------------

DROP TABLE [Domain].[DomainItem]
GO
-- ----------------------------------------------------------------------------------------------------------------
-- DROP tables for schema 'Specific' 
-- ----------------------------------------------------------------------------------------------------------------

DROP TABLE [Specific].[SpecificItem]
GO
*/
-- Remove the comment marker on the PREVIOUS line to enable DROP statements to remove existing elements

-- ###############################################################################################################
-- Create statements for catalogs, schemas, tables and sequences
-- ###############################################################################################################
-- ----------------------------------------------------------------------------------------------------------------
-- Catalog 'SimpleModel'
-- ----------------------------------------------------------------------------------------------------------------

USE master
GO
CREATE DATABASE [SimpleModel] /* ON PRIMARY (NAME=SimpleModel_dat, FILENAME='c:\mycatalogs\SimpleModel.mdf', SIZE=10MB) */
GO


USE [SimpleModel]
GO
-- ----------------------------------------------------------------------------------------------------------------
-- Schema 'Actor'
-- ----------------------------------------------------------------------------------------------------------------

CREATE SCHEMA [Actor] /* AUTHORIZATION owner_name */
GO

-- -------[ Tables ]-----------------------------------------------------------------------------------------------

CREATE TABLE [Actor].[Person] 
(
	[Firstname] [nvarchar] (MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[Id] [int] NOT NULL, 
	[Lastname] [nvarchar] (MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL 
)
GO
-- ----------------------------------------------------------------------------------------------------------------
-- Schema 'Core'
-- ----------------------------------------------------------------------------------------------------------------

CREATE SCHEMA [Core] /* AUTHORIZATION owner_name */
GO

-- -------[ Tables ]-----------------------------------------------------------------------------------------------

CREATE TABLE [Core].[Actor] 
(
	[CollectionId] [int] NOT NULL, 
	[Id] [int] IDENTITY (1,1) NOT NULL 
)
GO

CREATE TABLE [Core].[ActorIncident] 
(
	[ActorId] [int] NOT NULL, 
	[IncidentId] [int] NOT NULL, 
	[Id] [int] IDENTITY (1,1) NOT NULL 
)
GO

CREATE TABLE [Core].[Collection] 
(
	[Id] [int] IDENTITY (1,1) NOT NULL, 
	[Name] [nvarchar] (MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL 
)
GO

CREATE TABLE [Core].[Incident] 
(
	[CollectionId] [int] NOT NULL, 
	[Grouping] [int] NULL, 
	[Id] [int] IDENTITY (1,1) NOT NULL, 
	[ItemId] [int] NOT NULL 
)
GO

CREATE TABLE [Core].[Item] 
(
	[CollectionId] [int] NOT NULL, 
	[Description] [nvarchar] (MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
	[Id] [int] IDENTITY (1,1) NOT NULL 
)
GO
-- ----------------------------------------------------------------------------------------------------------------
-- Schema 'Domain'
-- ----------------------------------------------------------------------------------------------------------------

CREATE SCHEMA [Domain] /* AUTHORIZATION owner_name */
GO

-- -------[ Tables ]-----------------------------------------------------------------------------------------------

CREATE TABLE [Domain].[DomainItem] 
(
	[Id] [int] NOT NULL, 
	[OldItemId] [int] NOT NULL 
)
GO
-- ----------------------------------------------------------------------------------------------------------------
-- Schema 'Specific'
-- ----------------------------------------------------------------------------------------------------------------

CREATE SCHEMA [Specific] /* AUTHORIZATION owner_name */
GO

-- -------[ Tables ]-----------------------------------------------------------------------------------------------

CREATE TABLE [Specific].[SpecificItem] 
(
	[Id] [int] NOT NULL, 
	[Note] [nvarchar] (MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL 
)
GO

-- ###############################################################################################################
-- Create statements for Primary key constraints, Foreign key constraints, Unique constraints and Default Values
-- ###############################################################################################################
-- ----------------------------------------------------------------------------------------------------------------
-- Catalog 'SimpleModel'
-- ----------------------------------------------------------------------------------------------------------------

USE [SimpleModel]
GO
-- ----------------------------------------------------------------------------------------------------------------
-- Primary Key constraints for schema 'Actor'
-- ----------------------------------------------------------------------------------------------------------------

ALTER TABLE [Actor].[Person] WITH NOCHECK 
	ADD CONSTRAINT [PK_ff6ede44c30a985ceb4ad278be1] PRIMARY KEY CLUSTERED 
	( 
		[Id] 
	)
GO
-- ----------------------------------------------------------------------------------------------------------------
-- Unique constraints for schema 'Actor'
-- ----------------------------------------------------------------------------------------------------------------
-- ----------------------------------------------------------------------------------------------------------------
-- Default values for schema 'Actor'
-- ----------------------------------------------------------------------------------------------------------------
-- ----------------------------------------------------------------------------------------------------------------
-- Primary Key constraints for schema 'Core'
-- ----------------------------------------------------------------------------------------------------------------

ALTER TABLE [Core].[Actor] WITH NOCHECK 
	ADD CONSTRAINT [PK_2f1afa94f71a5cfe56bc667a45e] PRIMARY KEY CLUSTERED 
	( 
		[Id] 
	)
GO

ALTER TABLE [Core].[ActorIncident] WITH NOCHECK 
	ADD CONSTRAINT [PK_bdde2074218b2cb489e076854b6] PRIMARY KEY CLUSTERED 
	( 
		[Id] 
	)
GO

ALTER TABLE [Core].[Collection] WITH NOCHECK 
	ADD CONSTRAINT [PK_8d10ad74c2cb5e6ab8b97a4bd49] PRIMARY KEY CLUSTERED 
	( 
		[Id] 
	)
GO

ALTER TABLE [Core].[Incident] WITH NOCHECK 
	ADD CONSTRAINT [PK_c57402c47658caca4550139f517] PRIMARY KEY CLUSTERED 
	( 
		[Id] 
	)
GO

ALTER TABLE [Core].[Item] WITH NOCHECK 
	ADD CONSTRAINT [PK_afcd35a4a4b958670d1128179e5] PRIMARY KEY CLUSTERED 
	( 
		[Id] 
	)
GO
-- ----------------------------------------------------------------------------------------------------------------
-- Unique constraints for schema 'Core'
-- ----------------------------------------------------------------------------------------------------------------
-- ----------------------------------------------------------------------------------------------------------------
-- Default values for schema 'Core'
-- ----------------------------------------------------------------------------------------------------------------
-- ----------------------------------------------------------------------------------------------------------------
-- Primary Key constraints for schema 'Domain'
-- ----------------------------------------------------------------------------------------------------------------

ALTER TABLE [Domain].[DomainItem] WITH NOCHECK 
	ADD CONSTRAINT [PK_ade581347618a3a03e945bc69f8] PRIMARY KEY CLUSTERED 
	( 
		[Id] 
	)
GO
-- ----------------------------------------------------------------------------------------------------------------
-- Unique constraints for schema 'Domain'
-- ----------------------------------------------------------------------------------------------------------------
-- ----------------------------------------------------------------------------------------------------------------
-- Default values for schema 'Domain'
-- ----------------------------------------------------------------------------------------------------------------
-- ----------------------------------------------------------------------------------------------------------------
-- Primary Key constraints for schema 'Specific'
-- ----------------------------------------------------------------------------------------------------------------

ALTER TABLE [Specific].[SpecificItem] WITH NOCHECK 
	ADD CONSTRAINT [PK_1e57df54a14b46ffdfa2f1a7e87] PRIMARY KEY CLUSTERED 
	( 
		[Id] 
	)
GO
-- ----------------------------------------------------------------------------------------------------------------
-- Unique constraints for schema 'Specific'
-- ----------------------------------------------------------------------------------------------------------------
-- ----------------------------------------------------------------------------------------------------------------
-- Default values for schema 'Specific'
-- ----------------------------------------------------------------------------------------------------------------
-- ----------------------------------------------------------------------------------------------------------------
-- All foreign Key constraints
-- ----------------------------------------------------------------------------------------------------------------

ALTER TABLE [Actor].[Person] 
	ADD CONSTRAINT [FK_930af9146f7891519bfd539719f] FOREIGN KEY
	(
		[Id] 
	)
	REFERENCES [Core].[Actor]
	(
		[Id] 
	)
	ON DELETE CASCADE
	ON UPDATE NO ACTION
GO


ALTER TABLE [Core].[Actor] 
	ADD CONSTRAINT [FK_478661c40f1b8793b56a43db518] FOREIGN KEY
	(
		[CollectionId] 
	)
	REFERENCES [Core].[Collection]
	(
		[Id] 
	)
	ON DELETE CASCADE
	ON UPDATE NO ACTION
GO


ALTER TABLE [Core].[ActorIncident] 
	ADD CONSTRAINT [FK_86a475f4cfbb06ba18432b53145] FOREIGN KEY
	(
		[ActorId] 
	)
	REFERENCES [Core].[Actor]
	(
		[Id] 
	)
	ON DELETE CASCADE
	ON UPDATE NO ACTION
GO


ALTER TABLE [Core].[ActorIncident] 
	ADD CONSTRAINT [FK_a7d67124e8d860cbdc9a4fb9950] FOREIGN KEY
	(
		[IncidentId] 
	)
	REFERENCES [Core].[Incident]
	(
		[Id] 
	)
	ON DELETE CASCADE
	ON UPDATE NO ACTION
GO


ALTER TABLE [Core].[Incident] 
	ADD CONSTRAINT [FK_fb86340495bb80a0ec59eb4d91a] FOREIGN KEY
	(
		[ItemId] 
	)
	REFERENCES [Core].[Item]
	(
		[Id] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [Core].[Incident] 
	ADD CONSTRAINT [FK_fc9c98b4cffb675fe16927f55d6] FOREIGN KEY
	(
		[CollectionId] 
	)
	REFERENCES [Core].[Collection]
	(
		[Id] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [Core].[Item] 
	ADD CONSTRAINT [FK_fc808344380a37dec4d633ada36] FOREIGN KEY
	(
		[CollectionId] 
	)
	REFERENCES [Core].[Collection]
	(
		[Id] 
	)
	ON DELETE CASCADE
	ON UPDATE NO ACTION
GO


ALTER TABLE [Domain].[DomainItem] 
	ADD CONSTRAINT [FK_d12edd44b5aa5f0bf22b311ec9f] FOREIGN KEY
	(
		[Id] 
	)
	REFERENCES [Core].[Item]
	(
		[Id] 
	)
	ON DELETE CASCADE
	ON UPDATE NO ACTION
GO


ALTER TABLE [Specific].[SpecificItem] 
	ADD CONSTRAINT [FK_ed0220f42cab80268e8722796c0] FOREIGN KEY
	(
		[Id] 
	)
	REFERENCES [Domain].[DomainItem]
	(
		[Id] 
	)
	ON DELETE CASCADE
	ON UPDATE NO ACTION
GO

